[build]
  command = "npm install --legacy-peer-deps && npm run build-react"
  publish = "build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200